const fs   = require('fs');
const path = require('path');

const ROOT       = __dirname;
const SHADER_DIR = path.join(ROOT, 'shaders');
const BUNDLE     = path.join(SHADER_DIR, 'bundle.js');

function toTitle(filename) {
  return filename
    .replace(/\.glsl$/, '')
    .replace(/^\d+-/, '')
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

const files = fs.readdirSync(SHADER_DIR)
  .filter(f => f.endsWith('.glsl'))
  .sort((a, b) => parseInt(a) - parseInt(b));

const shaders = files.map(file => ({
  file,
  name: toTitle(file),
  frag: fs.readFileSync(path.join(SHADER_DIR, file), 'utf8').trim(),
}));

const entries = shaders.map(s =>
  `  { name: ${JSON.stringify(s.name)}, frag: ${JSON.stringify(s.frag)} }`
);
fs.writeFileSync(BUNDLE,
  `// Auto-generated by build.js — do not edit\nexport const SHADERS = [\n${entries.join(',\n')}\n];\n`
);

console.log(`bundle.js updated (${shaders.length} shaders):`);
shaders.forEach(s => console.log(`  ${s.file}  →  ${s.name}`));
